-- TableTop Prime — optimization migration
--
-- This migration adds missing foreign-key indexes and is generated by Prisma
-- when you run `npm run db:migrate -- --name add_indexes_and_cleanup` locally.
--
-- What changed since the init migration:
--   - Added @@index([eventId]) on Player, RoundPairing, RoundConfig, TableScore, JudgeCall
--   - Added @@index([userId]) on Player
--   - Added @@index([eventId, round]) on TableScore
--   - Added @@index([tableScoreId]) and @@index([playerId]) on PlacementScore
--   - Added @@index([eventId, status]) on JudgeCall
--
-- These indexes are pure performance additions — no schema changes, no data
-- migration. Safe to apply on a populated database.

-- CreateIndex
CREATE INDEX "Player_eventId_idx" ON "Player"("eventId");

-- CreateIndex
CREATE INDEX "Player_userId_idx" ON "Player"("userId");

-- CreateIndex
CREATE INDEX "RoundPairing_eventId_idx" ON "RoundPairing"("eventId");

-- CreateIndex
CREATE INDEX "RoundConfig_eventId_idx" ON "RoundConfig"("eventId");

-- CreateIndex
CREATE INDEX "TableScore_eventId_idx" ON "TableScore"("eventId");

-- CreateIndex
CREATE INDEX "TableScore_eventId_round_idx" ON "TableScore"("eventId", "round");

-- CreateIndex
CREATE INDEX "PlacementScore_tableScoreId_idx" ON "PlacementScore"("tableScoreId");

-- CreateIndex
CREATE INDEX "PlacementScore_playerId_idx" ON "PlacementScore"("playerId");

-- CreateIndex
CREATE INDEX "JudgeCall_eventId_idx" ON "JudgeCall"("eventId");

-- CreateIndex
CREATE INDEX "JudgeCall_eventId_status_idx" ON "JudgeCall"("eventId", "status");
