'use client'

/**
 * ShareButton — multi-purpose share component for the organizer dashboard.
 *
 * Opens a dropdown with a consistent set of options (in this order, everywhere
 * the ShareButton is used):
 *   - "Share link"      → Web Share API (native sheet on mobile, copy on desktop)
 *   - "Show QR code"    → modal with scannable QR
 *   - "Copy standings text" → clipboard (formatted for messaging apps)
 *   - "Copy pairings text"  → clipboard (current round tables)
 *
 * The standings/pairings items only appear when their data is available
 * (e.g. on the Standings tab vs the Pairings tab), but the order is always
 * the same — and the separator between share/QR and copy actions is shown
 * whenever either copy action is available.
 *
 * DRY: all share text is generated by lib/share/utils.ts.
 * All share actions go through the same webShare/copyToClipboard helpers.
 */
import * as React from 'react'
import { Share2, QrCode, ClipboardList, Clipboard } from 'lucide-react'
import { Button } from '@/components/ui/button'
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu'
import { useToast } from '@/hooks/use-toast'
import { useI18n } from '@/hooks/use-i18n'
import { QRCodeModal } from '@/lib/share/qr-modal'
import {
  webShare,
  copyToClipboard,
  buildShareUrl,
  formatStandingsText,
  formatPairingsText,
} from '@/lib/share/utils'

interface EventData {
  name: string
  gameName: string
  status: string
  currentRound: number
  totalRounds: number
  eventCode?: string | null
}

interface PairingData {
  round: number
  label: string | null
  isBonus: boolean
  tables: Array<{
    tableNumber: number
    playerIds: string[]
  }>
}

interface PlayerData {
  id: string
  name: string
  color: string
}

export function ShareButton({
  event,
  currentPairing,
  players,
  standings,
}: {
  event: EventData
  currentPairing?: PairingData | null
  players: PlayerData[]
  standings?: Array<{ name: string; color: string; total: number; gamePointsTotal: number; rounds: number }>
}) {
  const { toast } = useToast()
  const { t } = useI18n()
  const [qrOpen, setQrOpen] = React.useState(false)

  const shareUrl = event.eventCode ? buildShareUrl(event.eventCode) : ''

  const playerMap = new Map(players.map((p) => [p.id, p]))

  const handleShareLink = async () => {
    if (!shareUrl) return
    const result = await webShare(
      t('share.joinEvent').replace('{name}', event.name),
      t('share.joinEventBody').replace('{name}', event.name),
      shareUrl,
    )
    toast({
      title: result === 'shared' ? t('share.shared') : result === 'copied' ? t('share.linkCopied') : t('share.shareFailed'),
    })
  }

  const handleShowQR = () => {
    if (!shareUrl) return
    setQrOpen(true)
  }

  const handleCopyStandings = async () => {
    if (!standings || !shareUrl) return
    const text = formatStandingsText(event, standings, shareUrl)
    const ok = await copyToClipboard(text)
    toast(ok ? { title: t('share.standingsCopied') } : { title: t('share.copyFailed'), variant: 'destructive' })
  }

  const handleCopyPairings = async () => {
    if (!currentPairing || !shareUrl) return
    // Enrich pairing with player names
    const enriched = {
      round: currentPairing.round,
      label: currentPairing.label,
      isBonus: currentPairing.isBonus,
      tables: currentPairing.tables.map((tbl) => ({
        tableNumber: tbl.tableNumber,
        players: tbl.playerIds.map((id) => ({
          name: playerMap.get(id)?.name ?? t('common.unknown'),
          color: playerMap.get(id)?.color ?? 'bg-rose-500',
        })),
      })),
    }
    const text = formatPairingsText(event, enriched, shareUrl)
    const ok = await copyToClipboard(text)
    toast(ok ? { title: t('share.pairingsCopied') } : { title: t('share.copyFailed'), variant: 'destructive' })
  }

  if (!event.eventCode) return null

  const hasStandings = !!(standings && standings.length > 0)
  const hasPairings = !!currentPairing
  const showCopyGroup = hasStandings || hasPairings

  return (
    <>
      <DropdownMenu>
        <DropdownMenuTrigger asChild>
          <Button size="sm" variant="outline">
            <Share2 className="mr-1.5 h-3.5 w-3.5" />
            <span className="hidden sm:inline">{t('common.share')}</span>
          </Button>
        </DropdownMenuTrigger>
        <DropdownMenuContent align="end" className="w-56">
          <DropdownMenuLabel>{t('share.event')}</DropdownMenuLabel>
          <DropdownMenuItem onClick={handleShareLink}>
            <Share2 className="mr-2 h-3.5 w-3.5" /> {t('share.shareLink')}
          </DropdownMenuItem>
          <DropdownMenuItem onClick={handleShowQR}>
            <QrCode className="mr-2 h-3.5 w-3.5" /> {t('share.showQr')}
          </DropdownMenuItem>
          {showCopyGroup && <DropdownMenuSeparator />}
          {hasStandings && (
            <DropdownMenuItem onClick={handleCopyStandings}>
              <Clipboard className="mr-2 h-3.5 w-3.5" /> {t('share.copyStandings')}
            </DropdownMenuItem>
          )}
          {hasPairings && (
            <DropdownMenuItem onClick={handleCopyPairings}>
              <ClipboardList className="mr-2 h-3.5 w-3.5" /> {t('share.copyPairings')}
            </DropdownMenuItem>
          )}
        </DropdownMenuContent>
      </DropdownMenu>

      <QRCodeModal
        open={qrOpen}
        onOpenChange={setQrOpen}
        url={shareUrl}
        label={t('share.scanToJoin').replace('{name}', event.name)}
      />
    </>
  )
}
